/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Aplicacion.EstudiantesCSVInicio.listaCuentas;
import Modelo.Cuenta;
import Modelo.Excepciones.EntradaInvalidaExcepcion;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author lenin
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        lecturaCuentas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 100));
        setMaximumSize(new java.awt.Dimension(580, 550));
        setMinimumSize(new java.awt.Dimension(580, 550));
        setPreferredSize(new java.awt.Dimension(580, 550));
        setSize(new java.awt.Dimension(580, 550));
        getContentPane().setLayout(null);

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(130, 220, 320, 40);

        txtPassword.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(130, 312, 320, 40);

        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(210, 422, 160, 40);

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FrmLogin.png"))); // NOI18N
        getContentPane().add(lbFondo);
        lbFondo.setBounds(0, 0, 580, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lecturaCuentas(){
        try{
            File login = new File("src\\login.csv");
            Scanner scLogin = new Scanner(login);
            while(scLogin.hasNextLine()){
                String datosCuenta = scLogin.nextLine();
                Scanner scDatos = new Scanner(datosCuenta);
                scDatos.useDelimiter("\\s*,\\s*");
                String usuario = scDatos.next();
                String password = scDatos.next();
                char desencriptar[] = password.toCharArray();
                for(int i = 0; i < desencriptar.length; i++){
                    if ((int) desencriptar[i] % 2 == 0)
                        desencriptar[i] = (char) (desencriptar[i] + (char) 2);
                    if ((int) desencriptar[i] % 2 == 1)
                        desencriptar[i] = (char) (desencriptar[i] - (char) 2);
                }
                password = String.valueOf(desencriptar);
                Cuenta cuenta = new Cuenta(usuario, password);
                listaCuentas.add(cuenta);
            }
            scLogin.close();
        }catch(FileNotFoundException e1){
            e1.printStackTrace();
        }
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        int ingresa = -1;
        try{
            String usuarioTxt = this.txtUsuario.getText();
            String passwordTxt = String.valueOf(txtPassword.getPassword());
            if(usuarioTxt.isEmpty()||passwordTxt.isEmpty())
                throw new EntradaInvalidaExcepcion("Rellene todos los campos");
            for (int i = 0; i < listaCuentas.size(); i++) {
                if (usuarioTxt.equals(listaCuentas.get(i).getUsuario()) && passwordTxt.equals(listaCuentas.get(i).getPassword()))
                    ingresa = i;
            }
            if(ingresa == -1)
                JOptionPane.showMessageDialog(rootPane," El usuario o contraseña es incorrecta");
            else{
                new FrmCalificaciones().setVisible(true);
                this.dispose();
            }
        }catch(EntradaInvalidaExcepcion e2){
            JOptionPane.showMessageDialog(rootPane, e2.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
