/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Excepciones.EntradaInvalidaExcepcion;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author lenin
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtClave = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 100));
        setMaximumSize(new java.awt.Dimension(580, 550));
        setMinimumSize(new java.awt.Dimension(580, 550));
        setPreferredSize(new java.awt.Dimension(580, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(580, 550));
        getContentPane().setLayout(null);

        txtClave.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtClave.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBorder(null);
        txtClave.setOpaque(false);
        getContentPane().add(txtClave);
        txtClave.setBounds(170, 132, 210, 50);

        txtPassword.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setEnabled(false);
        txtPassword.setOpaque(false);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(150, 330, 310, 50);

        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(400, 132, 150, 50);

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.setEnabled(false);
        txtUsuario.setOpaque(false);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(150, 230, 310, 50);

        btnRegistrarse.setBorder(null);
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setEnabled(false);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse);
        btnRegistrarse.setBounds(90, 420, 160, 50);

        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(340, 420, 120, 50);

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FrmRegistro.png"))); // NOI18N
        getContentPane().add(lbFondo);
        lbFondo.setBounds(0, 0, 580, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        String claveTxt = String.valueOf(txtClave.getPassword());
        if(claveTxt.equals("registro2020")){
            this.txtClave.setEnabled(false);
            this.btnEntrar.setEnabled(false);
            this.txtUsuario.setEnabled(true);
            this.txtPassword.setEnabled(true);
            this.btnRegistrarse.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Clave correcta, puede continuar con el registro");
        }else
            JOptionPane.showMessageDialog(rootPane, "La clave ingresada es incorrecta");
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        try{
            String usuarioTxt = this.txtUsuario.getText();
            String passwordTxt = String.valueOf(txtPassword.getPassword());
            if(usuarioTxt.isEmpty()||passwordTxt.isEmpty())
                throw new EntradaInvalidaExcepcion("Rellene todos los campos");
            FileWriter registroCSV = new FileWriter("src\\archivos\\login.csv", true);
            PrintWriter escribir = new PrintWriter(registroCSV);
            char encriptar[] = passwordTxt.toCharArray();
            for(int i = 0; i < encriptar.length; i++) {
                if ((int) encriptar[i] % 2 == 0)
                    encriptar[i] = (char) (encriptar[i] - (char) 2);
                if ((int) encriptar[i] % 2 == 1)
                   encriptar[i] = (char) (encriptar[i] + (char) 2);
            }
            passwordTxt = String.valueOf(encriptar);
            escribir.println(usuarioTxt + "," + passwordTxt);
            JOptionPane.showMessageDialog(rootPane, "La cuenta ha sido registrada con exito");
            registroCSV.close();
        }catch(EntradaInvalidaExcepcion e1){
            JOptionPane.showMessageDialog(rootPane, e1.getMessage());
        }catch(IOException e2){
            JOptionPane.showMessageDialog(rootPane, "Problemas con la creación del archivo de salida");
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
